gas_stations.gas_stations_provincias_type.*:
  type: config_entity
  label: 'Provincias type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
